virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy

language: python
python:
    - "2.7"
    - "3.3"

install: "pip install numpy; pip install cython; pip install -r requirements.txt"
script: "python -m unittest discover"

